### ISSUE TITLE
Trying to xpub-derive hardened key could use better error message

### ISSUE THREAD

**Issue by laanwj** [darosior/python-bip32#9]
Obviously this is impossible, but the current `AssertionError` is not very clear.
```python
>>> bipp = BIP32.from_xpub("xpub6AFtDPwErcEhAY71AQoj83J9E63eLrRwqDar7zi2Ds9GWa3PqjwvPGLs4KrKvaZCojRzKAHSvQ9QEat4NPjvwc3D1ZFYcStbQJki2gxnd62")
>>> bipp.get_xpub_from_path("m/0'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/store/orion/projects/bitcoin/experiment/pbip32/venv/lib/python3.8/site-packages/bip32/bip32.py", line 154, in get_xpub_from_path
    chaincode, pubkey = self.get_extended_pubkey_from_path(path)
  File "/store/orion/projects/bitcoin/experiment/pbip32/venv/lib/python3.8/site-packages/bip32/bip32.py", line 93, in get_extended_pubkey_from_path
    _derive_hardened_private_child(key, chaincode, index)
  File "/store/orion/projects/bitcoin/experiment/pbip32/venv/lib/python3.8/site-packages/bip32/utils.py", line 62, in _derive_hardened_private_child
    assert isinstance(privkey, bytes) and isinstance(chaincode, bytes)
AssertionError
```

**Comment by darosior** [comment]
Fixed in #11 if you have a second to skim through it (suggestions on the approach welcome).
